Repository Amsterdam-Team/The-Cute-Tudee, pull requests merged in 2025-06, with the labels that each got.

#6 Den haag feature/add app colors
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/DarkThemeColors.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/LightThemeColors.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/colors/CuteTudeeAppColors.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/colors/DarkThemeColors.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/colors/LightThemeColors.kt
Labels: feature

#8 Utrecht-feature/domain
  app/src/main/java/com/amsterdam/cutetudee/data/repository/CategoryRepositoryImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/data/repository/TaskRepositoryImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/exception/Exceptions.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/model/Category.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/model/Task.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/repository/CategoryRepository.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/repository/TaskRepository.kt
Labels: feature

#14 add app-wide default typography
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/textStyle/DefaultTextStyle.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/textStyle/TudeeTextStyle.kt
  app/src/main/res/font/font.xml
  app/src/main/res/font/nunito_medium.ttf
  app/src/main/res/font/nunito_regular.ttf
  app/src/main/res/font/nunito_semi_bold.ttf
Labels: feature

#32 Rotterdam- add task status components
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/tast_status/TaskStatusChip.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/tast_status/TaskStatusUi.kt
Labels: feature

#49 Rotterdam- Add Task Card Component
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/DateChip.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/task_card/TaskItemCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/task_card/TaskItemUiState.kt
Labels: feature

#51 Rotterdam- Add floating action button
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TudeeFloatingActionButton.kt
Labels: feature

#64 Rotterdam- Updated CustomSnackBar action
  app/src/main/java/com/amsterdam/cutetudee/presentation/CuteTudeeApp.kt
Labels: enhancement

#69 Rotterdam- Added animated theme switcher button
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/SwitchThemeButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/theme_swithcer/ThemeSwitcherButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/theme_swithcer/ThemeSwitcherClouds.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/theme_swithcer/ThemeSwitcherMoon.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/theme_swithcer/ThemeSwitcherMoonCircles.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/theme_swithcer/ThemeSwitcherStars.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/theme_swithcer/ThemeSwitcherSun.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/AnimateAlignmentAsState.kt
Labels: feature

#68 Utrecht update/bottom sheet
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/ConfiormationMessageContainer.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/ConfirmationBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/ConfirmationButtonsContainer.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/DeleteConfirmationBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/NoTasksContainer.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/Extensions.kt
Labels: enhancement

#73 Rotterdam- Update Task Card to swipe to reveal component
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TaskItemCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/DateChip.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/task_card/TaskItemCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/task_card/TaskItemUiState.kt
Labels: enhancement

#59 Utrecht feature/data
  app/build.gradle.kts
  app/src/main/assets/database/TudeeDatabase.db
  app/src/main/java/com/amsterdam/cutetudee/data/local/converters/Converters.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/dao/CategoryDao.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/dao/TaskDao.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/entity/CategoryEntity.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/entity/TaskEntity.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/roomDB/LocalDatabase.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/roomDB/TudeeDatabase.kt
  app/src/main/java/com/amsterdam/cutetudee/data/mapper/CategoryMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/data/mapper/TaskMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/data/repository/AppSettingsServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/data/repository/CategoryServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/data/repository/TaskServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/CategoryServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/TaskServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/di/DataModule.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/model/Category.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/AppSettingsService.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/CategoryService.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/TaskService.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/BitmapMapper.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feature

#75 Den Haag- add custom date picker dialog
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomDatePickerDialog.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/DateTimeHandler.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/IDateTimeHandler.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#70 Utrecht feature/onboarding
  app/src/main/java/com/amsterdam/cutetudee/di/UiModule.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/Spacer.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/onboarding/OnboardingCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/onboarding/OnboardingImage.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/onboarding/OnboardingIndicators.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnboardingUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/AppTheme.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/CuteTudeeTheme.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/images/CuteTudeeAppImages.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/images/DarkThemeImages.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/images/LightThemeImages.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#81 Rotterdam- Updated dependency injection
  app/src/main/java/com/amsterdam/cutetudee/di/DataModule.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingViewModel.kt
Labels: enhancement

#80 Rotterdam- Updated DB schema
  app/src/main/java/com/amsterdam/cutetudee/data/local/entity/CategoryEntity.kt
Labels: enhancement

#76 Den haag feature/category details
  app/src/main/java/com/amsterdam/cutetudee/di/UiModule.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/navigation/NavGraph.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoreyDetailsScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/component/HorizontalTabs.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/component/TabItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/component/TopAppBar.kt
Labels: feature

#83 Rotterdam- Implement task screen
  app/build.gradle.kts
  app/src/main/java/com/amsterdam/cutetudee/data/local/dao/CategoryDao.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/CategoryServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/di/DataModule.kt
  app/src/main/java/com/amsterdam/cutetudee/di/UiModule.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/model/Task.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/CategoryService.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/NoTasksContainer.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/priority/PriorityUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/tast_status/TaskStatusUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/model/CategoryUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/model/TaskUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/DateTimeHandler.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/DateTimeUtils.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/Extensions.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/IDateTimeHandler.kt
  gradle/libs.versions.toml
Labels: enhancement, feature

#84 Utrecht feature/splash screen
  app/src/main/java/com/amsterdam/cutetudee/di/UiModule.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/navigation/NavGraph.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/navigation/Screen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/splash/SplashScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/splash/SplashScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/splash/SplashViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/textStyle/DefaultTextStyle.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/textStyle/TudeeTextStyle.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#85 Rotterdam feature/implement add and edit task
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/BadgedCategoryItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CategoryItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/ReadOnlyCustomTextField.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/SelectedBadgedCategory.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/AddEditTaskUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/AddEditTaskViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/AddOrEditTaskBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/DateTimeHandler.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/IDateTimeHandler.kt
  app/src/main/res/drawable/calendar_add_icon.xml
Labels: feature

#88 Utrecht-feature/home-screen
  app/build.gradle.kts
  app/src/main/java/com/amsterdam/cutetudee/MainActivity.kt
  app/src/main/java/com/amsterdam/cutetudee/MainViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/di/DataModule.kt
  app/src/main/java/com/amsterdam/cutetudee/di/UiModule.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/CuteTudeeApp.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/ProgressBar.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/AppBar.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/IconDateTask.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/ImageMood.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/OverlayBoxContent.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/OverviewCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TaskSection.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TextLabelTaskProgress.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TextMoodIcon.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TextWithArrowIcon.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TopCuteTudeeAppBar.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/ThemeManager.kt
  app/src/main/res/drawable/arrow.xml
Labels: feature

#91 Rotterdam- Refactor TaskDetailsBottomSheet and TaskDetailsUiState to use TaskUi
  app/src/main/java/com/amsterdam/cutetudee/presentation/bottomSheets/taskDetails/TaskDetailsBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/bottomSheets/taskDetails/TaskDetailsUiState.kt
Labels: enhancement

#98 Update task screen padding
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
Labels: enhancement

#95 Rotterdam- Implement task details and edit flow
  app/src/main/java/com/amsterdam/cutetudee/presentation/bottomSheets/taskDetails/TaskDetailsBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/priority/PriorityUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/tast_status/TaskStatusUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/model/TaskUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
Labels: enhancement

#101 Rotterdam- Fix screen top padding issue
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
Labels: bug

#105 Fix enable screen orientation
  app/src/main/java/com/amsterdam/cutetudee/MainActivity.kt
Labels: bug

#100 Rotterdam- Refactor task screen
  app/src/main/java/com/amsterdam/cutetudee/presentation/bottomSheets/taskDetails/TaskDetailsBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TaskItemCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
Labels: bug

#109 Den-Haag- remove ThemeMode enum and make the functions deal with it as Boolean.
  app/src/main/java/com/amsterdam/cutetudee/data/local/datastore/DataStore.kt
  app/src/main/java/com/amsterdam/cutetudee/data/repository/AppSettingsServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/model/ThemeMode.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/AppSettingsService.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/ThemeManager.kt
Labels: enhancement

#111 Rotterdam- remove redundant dismiss logic in ConfirmationBottomSheet
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/ConfirmationBottomSheet.kt
Labels: bug, enhancement

#116 Rotterdam- Fix system status bar icons color
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/CuteTudeeTheme.kt
Labels: bug

#112 Den-Haag- add nav controller to local composition provider
  app/src/main/java/com/amsterdam/cutetudee/presentation/CuteTudeeApp.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/navigation/NavGraph.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/splash/SplashScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/splash/SplashScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreenRoute.kt
Labels: enhancement

#119 Rotterdam- Fixed chips onclick ribble
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/BasicChip.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/DateChip.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/priority/PriorityChip.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/tast_status/TaskStatusChip.kt
Labels: bug, enhancement

#118 Rotterdam- Fixed buttons ribble and Added enhancements
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomFloatingActionButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/GradientFilledButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/OutlineButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TudeeTextButton.kt
Labels: bug, enhancement

#121 Rotterdam- Fixed image size of task item card
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TaskItemCard.kt
Labels: bug, enhancement

#122 Rotterdam- Fixed custom text field
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomTextField.kt
Labels: bug, enhancement

#126 Utrecht-update/data-store-preferences
  app/src/main/java/com/amsterdam/cutetudee/MainViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/datastore/AppPreferences.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/datastore/DataStore.kt
  app/src/main/java/com/amsterdam/cutetudee/data/repository/AppSettingsServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/AppSettingsServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/di/DataModule.kt
  app/src/main/java/com/amsterdam/cutetudee/di/ServiceModule.kt
  app/src/main/java/com/amsterdam/cutetudee/di/UtilsModule.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/AppSettingsService.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/CuteTudeeApp.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/ThemeManager.kt
Labels: bug, enhancement

#107 Utrecht refactor/service
  app/src/main/java/com/amsterdam/cutetudee/data/local/dao/CategoryDao.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/dao/TaskDao.kt
  app/src/main/java/com/amsterdam/cutetudee/data/local/entity/CategoryWithTaskCount.kt
  app/src/main/java/com/amsterdam/cutetudee/data/mapper/CategoryMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/CategoryServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/TaskServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/model/TaskStatistics.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/TaskService.kt
Labels: feature

#113 Rotterdam- Fix task lazy grid and enhance task card ui
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TaskItemCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TaskSection.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
Labels: bug, enhancement

#123 Utrecht refactor/tasks screen
  app/src/main/java/com/amsterdam/cutetudee/presentation/bottomSheets/taskDetails/TaskDetailsBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/model/TaskUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksEffect.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksInteraction.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
Labels: bug, enhancement

#114 Rotterdam- Fix task screen navigation
  app/src/main/java/com/amsterdam/cutetudee/presentation/navigation/Screen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TaskSection.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TextLabelTaskProgress.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TextWithArrowIcon.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
Labels: bug, enhancement

#106 Rotterdam- update and refactor category details
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/composables/AddEditCategoryBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsEffect.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsInteractionListener.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsViewModel.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/file_paths.xml
Labels: enhancement

#133 Den Haag- update ThemeMode to be enum in utils.
  app/src/main/java/com/amsterdam/cutetudee/MainViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/data/mapper/ThemeModeMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/AppSettingsServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/AppSettingsService.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/utils/ThemeMode.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeViewModel.kt
Labels: enhancement

#134 Den Haag- replace the date time handler functions to be extension functions
  app/src/main/java/com/amsterdam/cutetudee/di/UtilsModule.kt
  app/src/main/java/com/amsterdam/cutetudee/di/ViewModelModule.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomDatePickerDialog.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/AddEditTaskUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/AddEditTaskViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/AddOrEditTaskBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/DateTimeHandler.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/DateTimeUtils.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/IDateTimeHandler.kt
Labels: enhancement

#132 Utrecht-update/splash-screen
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/splash/SplashScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/splash/SplashViewModel.kt
Labels: enhancement

#131 Utrecht-update/update-on-boarding
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/onboarding/OnboardingCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingInteractionListener.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnboardingUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/component/OnboardingCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/component/OnboardingImage.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/component/OnboardingIndicators.kt
Labels: enhancement

#136 Den Haag- rename and restructure classes and packages
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/amsterdam/cutetudee/data/local/roomDB/TudeeDatabase.kt
  app/src/main/java/com/amsterdam/cutetudee/data/mapper/CategoryMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/data/mapper/TaskMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/CategoryServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/data/service/TaskServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/di/AppModule.kt
  app/src/main/java/com/amsterdam/cutetudee/di/UtilsModule.kt
  app/src/main/java/com/amsterdam/cutetudee/di/ViewModelModule.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/entity/Category.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/entity/Task.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/entity/TaskStatistics.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/CategoryService.kt
  app/src/main/java/com/amsterdam/cutetudee/domain/service/TaskService.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/AppViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/CuteTudeeApp.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/CuteTudeeApplication.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/MainActivity.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/priority/PriorityChip.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/priority/PriorityUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/tast_status/TaskStatusChip.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/chip/tast_status/TaskStatusUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/custom_padding/BottomNavigationBarPadding.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/model/CategoryUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/model/TaskUi.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/navigation/BottomNavigationItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/navigation/CuteTudeeBottomNavigation.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/component/AddEditCategoryBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/component/ImagePicker.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/mappers/CategoryMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsInteractionListener.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/common/AddEditInteractionListener.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/common/AddEditTaskUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/component/AddOrEditTaskBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/OverlayBoxContent.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/OverviewCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/theme_swithcer/ThemeSwitcherButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksEffect.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksInteraction.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/BitmapMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/NoRippleInteractionSource.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/PresentationConstants.kt
Labels: enhancement

#140 Rotterdam fix/fix category item
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/BadgedCategoryItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CategoryItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/SelectedBadgedCategory.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/component/AddOrEditTaskBottomSheet.kt
Labels: bug, enhancement

#143 Dan-Haag-refactor/text-field-limititions
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/component/AddEditCategoryBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/component/AddOrEditTaskBottomSheet.kt
Labels: enhancement

#153 Rotterdam- Fix add task default date
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
Labels: bug

#156 Rotterdam- Improve Transitions and Interaction Animations
  app/src/main/java/com/amsterdam/cutetudee/presentation/bottomSheets/taskDetails/TaskDetailsBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/ConfirmationBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomFloatingActionButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomTextField.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/GradientFilledButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/OutlineButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/SelectedBadgedCategory.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TabsContent.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TudeeTextButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
Labels: enhancement

#151 Rotterdam- Added window insets padding to CustomBottomSheet
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomBottomSheet.kt
Labels: enhancement

#150 Rotterdam- Fixed category item ripple effect
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/BadgedCategoryItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CategoryItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/SelectedBadgedCategory.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryScreen.kt
Labels: enhancement

#148 Den Haag- Make task item clickable in home screen
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeEffect.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeMapper.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreenInteraction.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TaskSection.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, feature

#158 refactor AppPreferences to use PreferencesKeys for better readability
  app/src/main/java/com/amsterdam/cutetudee/data/local/datastore/AppPreferences.kt
Labels: enhancement

#160 Utrecht-update-home-screen-top-app-bar
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TopCuteTudeeAppBar.kt
Labels: enhancement

#161 Rotterdam- Fix home task grid
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TaskItemCard.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TaskSection.kt
Labels: bug

#162 Rotterdam- Updated category grid to be adaptive
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/AddOrEditTaskBottomSheet.kt
Labels: enhancement

#170 Rotterdam- Prevent User to Add Task In Past Dates
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksEffect.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#173 Dan-Haag-refactor/ripple-enhancment
  app/src/main/java/com/amsterdam/cutetudee/presentation/navigation/BottomNavigationItem.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/NoRippleInteractionSource.kt
Labels: enhancement

#176 Rotterdam bugfix/fix date selection error
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
Labels: bug

#179 Rotterdam- Fixed spacing in HomeScreen
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/component/TopCuteTudeeAppBar.kt
Labels: bug

#180 Den Haag- fix add and edit task bugs
  app/src/main/java/com/amsterdam/cutetudee/presentation/bottomSheets/taskDetails/TaskDetailsBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/AddOrEditTaskBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/common/AddEditTaskUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeScreenInteraction.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/home/HomeViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksInteraction.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksUiState.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksViewModel.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/DateTimeUtils.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/Extensions.kt
Labels: bug, enhancement

#182 Rotterdam- Refactored code
  app/src/main/java/com/amsterdam/cutetudee/data/service/TaskServiceImpl.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/CuteTudeeApp.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/MainActivity.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/bottomSheets/taskDetails/TaskDetailsBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/AddOrEditTaskBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/ConfirmationBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/CustomFloatingActionButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/GradientFilledButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/OutlineButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TabsContent.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/component/TudeeTextButton.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/CategoryScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/category/component/AddEditCategoryBottomSheet.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/CategoryDetailsScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/component/HorizontalTabs.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/categoryDetails/component/TopAppBar.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/onBoarding/OnBoardingScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/splash/SplashScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/screens/tasks/TasksScreenRoute.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/theme/CuteTudeeTheme.kt
  app/src/main/java/com/amsterdam/cutetudee/presentation/utils/Extensions.kt
Labels: enhancement
